[2024-06-02T12:01:25.492+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T12:01:25.541+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T05:30:00+00:00 [queued]>
[2024-06-02T12:01:25.561+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T05:30:00+00:00 [queued]>
[2024-06-02T12:01:25.562+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-02T12:01:25.701+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 05:30:00+00:00
[2024-06-02T12:01:25.710+0000] {standard_task_runner.py:63} INFO - Started process 2477 to run task
[2024-06-02T12:01:25.717+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T05:30:00+00:00', '--job-id', '809', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmpt_j2_te5']
[2024-06-02T12:01:25.719+0000] {standard_task_runner.py:91} INFO - Job 809: Subtask check_status
[2024-06-02T12:01:25.844+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T05:30:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T12:01:26.025+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T05:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T05:30:00+00:00'
[2024-06-02T12:01:26.026+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T12:01:26.053+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T12:01:26.054+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_docker_operator.py", line 24, in check_send_status
    raise ValueError(f"Check send status failed: {result}")
ValueError: Check send status failed: {'status': 'failed'}
[2024-06-02T12:01:26.079+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T05:30:00+00:00, execution_date=20240601T053000, start_date=20240602T120125, end_date=20240602T120126
[2024-06-02T12:01:26.151+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 809 for task check_status (Check send status failed: {'status': 'failed'}; 2477)
[2024-06-02T12:01:26.171+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-02T12:01:26.221+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T12:01:26.224+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-02T12:21:26.673+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T12:21:26.721+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T05:30:00+00:00 [queued]>
[2024-06-02T12:21:26.744+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T05:30:00+00:00 [queued]>
[2024-06-02T12:21:26.745+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-02T12:21:26.801+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 05:30:00+00:00
[2024-06-02T12:21:26.808+0000] {standard_task_runner.py:63} INFO - Started process 3013 to run task
[2024-06-02T12:21:26.812+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T05:30:00+00:00', '--job-id', '810', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmp6xxxzlmj']
[2024-06-02T12:21:26.815+0000] {standard_task_runner.py:91} INFO - Job 810: Subtask check_status
[2024-06-02T12:21:27.120+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T05:30:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T12:21:27.801+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T05:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T05:30:00+00:00'
[2024-06-02T12:21:27.803+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T12:21:27.844+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T12:21:27.846+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_docker_operator.py", line 24, in check_send_status
    raise ValueError(f"Check send status failed: {result}")
ValueError: Check send status failed: {'status': 'failed'}
[2024-06-02T12:21:27.872+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T05:30:00+00:00, execution_date=20240601T053000, start_date=20240602T122126, end_date=20240602T122127
[2024-06-02T12:21:27.930+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 810 for task check_status (Check send status failed: {'status': 'failed'}; 3013)
[2024-06-02T12:21:27.951+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-02T12:21:28.154+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T12:21:28.157+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
