[2024-05-30T14:35:54.424+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-30T14:35:54.480+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monitor_containers.check_kafka scheduled__2023-01-01T06:10:00+00:00 [queued]>
[2024-05-30T14:35:54.531+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monitor_containers.check_kafka scheduled__2023-01-01T06:10:00+00:00 [queued]>
[2024-05-30T14:35:54.532+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-05-30T14:35:54.628+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): check_kafka> on 2023-01-01 06:10:00+00:00
[2024-05-30T14:35:54.639+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'monitor_containers', 'check_kafka', 'scheduled__2023-01-01T06:10:00+00:00', '--job-id', '527', '--raw', '--subdir', 'DAGS_FOLDER/flask_monitoring.py', '--cfg-path', '/tmp/tmp93xiuxjh']
[2024-05-30T14:35:54.642+0000] {standard_task_runner.py:91} INFO - Job 527: Subtask check_kafka
[2024-05-30T14:35:54.644+0000] {standard_task_runner.py:63} INFO - Started process 2400 to run task
[2024-05-30T14:35:54.813+0000] {task_command.py:426} INFO - Running <TaskInstance: monitor_containers.check_kafka scheduled__2023-01-01T06:10:00+00:00 [running]> on host f708138922bb
[2024-05-30T14:35:55.108+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='monitor_containers' AIRFLOW_CTX_TASK_ID='check_kafka' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T06:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T06:10:00+00:00'
[2024-05-30T14:35:55.110+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-30T14:35:55.152+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-30T14:35:55.154+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker ps | grep kafka || exit 1']
[2024-05-30T14:35:55.169+0000] {subprocess.py:86} INFO - Output:
[2024-05-30T14:35:55.198+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2024-05-30T14:35:55.200+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-30T14:35:55.202+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-30T14:35:55.240+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-30T14:35:55.259+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=monitor_containers, task_id=check_kafka, run_id=scheduled__2023-01-01T06:10:00+00:00, execution_date=20230101T061000, start_date=20240530T143554, end_date=20240530T143555
[2024-05-30T14:35:55.359+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 527 for task check_kafka (Bash command failed. The command returned a non-zero exit code 1.; 2400)
[2024-05-30T14:35:55.383+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-30T14:35:55.472+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-30T14:35:55.527+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
