[2024-05-30T14:25:09.841+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-30T14:25:09.974+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monitor_containers.check_kafka scheduled__2023-01-01T04:10:00+00:00 [queued]>
[2024-05-30T14:25:10.055+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monitor_containers.check_kafka scheduled__2023-01-01T04:10:00+00:00 [queued]>
[2024-05-30T14:25:10.056+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-30T14:25:10.232+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): check_kafka> on 2023-01-01 04:10:00+00:00
[2024-05-30T14:25:10.242+0000] {standard_task_runner.py:63} INFO - Started process 1774 to run task
[2024-05-30T14:25:10.246+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'monitor_containers', 'check_kafka', 'scheduled__2023-01-01T04:10:00+00:00', '--job-id', '481', '--raw', '--subdir', 'DAGS_FOLDER/monitor_containers.py', '--cfg-path', '/tmp/tmpzwta696_']
[2024-05-30T14:25:10.249+0000] {standard_task_runner.py:91} INFO - Job 481: Subtask check_kafka
[2024-05-30T14:25:10.545+0000] {task_command.py:426} INFO - Running <TaskInstance: monitor_containers.check_kafka scheduled__2023-01-01T04:10:00+00:00 [running]> on host f708138922bb
[2024-05-30T14:25:11.119+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='monitor_containers' AIRFLOW_CTX_TASK_ID='check_kafka' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T04:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T04:10:00+00:00'
[2024-05-30T14:25:11.121+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-30T14:25:11.168+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-30T14:25:11.171+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker ps | grep kafka || exit 1']
[2024-05-30T14:25:11.191+0000] {subprocess.py:86} INFO - Output:
[2024-05-30T14:25:11.248+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2024-05-30T14:25:11.255+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-30T14:25:11.258+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-30T14:25:11.311+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-30T14:25:11.328+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=monitor_containers, task_id=check_kafka, run_id=scheduled__2023-01-01T04:10:00+00:00, execution_date=20230101T041000, start_date=20240530T142509, end_date=20240530T142511
[2024-05-30T14:25:11.592+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 481 for task check_kafka (Bash command failed. The command returned a non-zero exit code 1.; 1774)
[2024-05-30T14:25:11.628+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-30T14:25:11.885+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-30T14:25:11.889+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
