[2024-05-30T14:33:25.306+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-30T14:33:25.388+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: monitor_containers.check_kafka scheduled__2023-01-01T07:50:00+00:00 [queued]>
[2024-05-30T14:33:25.421+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: monitor_containers.check_kafka scheduled__2023-01-01T07:50:00+00:00 [queued]>
[2024-05-30T14:33:25.422+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-30T14:33:25.529+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): check_kafka> on 2023-01-01 07:50:00+00:00
[2024-05-30T14:33:25.535+0000] {standard_task_runner.py:63} INFO - Started process 2320 to run task
[2024-05-30T14:33:25.538+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'monitor_containers', 'check_kafka', 'scheduled__2023-01-01T07:50:00+00:00', '--job-id', '521', '--raw', '--subdir', 'DAGS_FOLDER/monitor_containers.py', '--cfg-path', '/tmp/tmpyu89wwc8']
[2024-05-30T14:33:25.541+0000] {standard_task_runner.py:91} INFO - Job 521: Subtask check_kafka
[2024-05-30T14:33:25.698+0000] {task_command.py:426} INFO - Running <TaskInstance: monitor_containers.check_kafka scheduled__2023-01-01T07:50:00+00:00 [running]> on host f708138922bb
[2024-05-30T14:33:25.999+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='monitor_containers' AIRFLOW_CTX_TASK_ID='check_kafka' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T07:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T07:50:00+00:00'
[2024-05-30T14:33:26.000+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-30T14:33:26.018+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-30T14:33:26.019+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker ps | grep kafka || exit 1']
[2024-05-30T14:33:26.031+0000] {subprocess.py:86} INFO - Output:
[2024-05-30T14:33:26.049+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2024-05-30T14:33:26.050+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-30T14:33:26.051+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-30T14:33:26.069+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-30T14:33:26.077+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=monitor_containers, task_id=check_kafka, run_id=scheduled__2023-01-01T07:50:00+00:00, execution_date=20230101T075000, start_date=20240530T143325, end_date=20240530T143326
[2024-05-30T14:33:26.146+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 521 for task check_kafka (Bash command failed. The command returned a non-zero exit code 1.; 2320)
[2024-05-30T14:33:26.193+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-30T14:33:26.232+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-30T14:33:26.234+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
