[2024-06-02T12:07:44.447+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T12:07:44.491+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T10:00:00+00:00 [queued]>
[2024-06-02T12:07:44.510+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T10:00:00+00:00 [queued]>
[2024-06-02T12:07:44.511+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-02T12:07:44.665+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 10:00:00+00:00
[2024-06-02T12:07:44.670+0000] {standard_task_runner.py:63} INFO - Started process 2670 to run task
[2024-06-02T12:07:44.673+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T10:00:00+00:00', '--job-id', '844', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmpij0ail4q']
[2024-06-02T12:07:44.675+0000] {standard_task_runner.py:91} INFO - Job 844: Subtask check_status
[2024-06-02T12:07:44.788+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T10:00:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T12:07:44.979+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T10:00:00+00:00'
[2024-06-02T12:07:44.980+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T12:07:45.006+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T12:07:45.007+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_docker_operator.py", line 24, in check_send_status
    raise ValueError(f"Check send status failed: {result}")
ValueError: Check send status failed: {'status': 'failed'}
[2024-06-02T12:07:45.031+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T10:00:00+00:00, execution_date=20240601T100000, start_date=20240602T120744, end_date=20240602T120745
[2024-06-02T12:07:45.083+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 844 for task check_status (Check send status failed: {'status': 'failed'}; 2670)
[2024-06-02T12:07:45.127+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-02T12:07:45.156+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T12:07:45.159+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-02T12:27:12.808+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T12:27:12.879+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T10:00:00+00:00 [queued]>
[2024-06-02T12:27:12.900+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T10:00:00+00:00 [queued]>
[2024-06-02T12:27:12.902+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-02T12:27:12.958+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 10:00:00+00:00
[2024-06-02T12:27:12.964+0000] {standard_task_runner.py:63} INFO - Started process 3188 to run task
[2024-06-02T12:27:12.967+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T10:00:00+00:00', '--job-id', '842', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmpdvgyxw07']
[2024-06-02T12:27:12.969+0000] {standard_task_runner.py:91} INFO - Job 842: Subtask check_status
[2024-06-02T12:27:13.398+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T10:00:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T12:27:13.576+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T10:00:00+00:00'
[2024-06-02T12:27:13.577+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T12:27:13.600+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T12:27:13.603+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_docker_operator.py", line 24, in check_send_status
    raise ValueError(f"Check send status failed: {result}")
ValueError: Check send status failed: {'status': 'failed'}
[2024-06-02T12:27:13.625+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T10:00:00+00:00, execution_date=20240601T100000, start_date=20240602T122712, end_date=20240602T122713
[2024-06-02T12:27:13.678+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 842 for task check_status (Check send status failed: {'status': 'failed'}; 3188)
[2024-06-02T12:27:13.710+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-02T12:27:13.850+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T12:27:13.855+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
