[2024-06-02T11:58:45.902+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T11:58:45.999+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T02:00:00+00:00 [queued]>
[2024-06-02T11:58:46.023+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T02:00:00+00:00 [queued]>
[2024-06-02T11:58:46.024+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-02T11:58:46.125+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 02:00:00+00:00
[2024-06-02T11:58:46.132+0000] {standard_task_runner.py:63} INFO - Started process 2390 to run task
[2024-06-02T11:58:46.136+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T02:00:00+00:00', '--job-id', '793', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmpyfjp567u']
[2024-06-02T11:58:46.138+0000] {standard_task_runner.py:91} INFO - Job 793: Subtask check_status
[2024-06-02T11:58:46.494+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T02:00:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T11:58:46.684+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T02:00:00+00:00'
[2024-06-02T11:58:46.685+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T11:58:46.725+0000] {python.py:237} INFO - Done. Returned value was: {'status': 'success'}
[2024-06-02T11:58:46.727+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T11:58:46.885+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T02:00:00+00:00, execution_date=20240601T020000, start_date=20240602T115846, end_date=20240602T115846
[2024-06-02T11:58:47.036+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-02T11:58:47.185+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T11:58:47.187+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-02T12:19:15.056+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T12:19:15.103+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T02:00:00+00:00 [queued]>
[2024-06-02T12:19:15.126+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T02:00:00+00:00 [queued]>
[2024-06-02T12:19:15.127+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-02T12:19:15.196+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-01 02:00:00+00:00
[2024-06-02T12:19:15.203+0000] {standard_task_runner.py:63} INFO - Started process 2935 to run task
[2024-06-02T12:19:15.206+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_docker_operator', 'check_status', 'scheduled__2024-06-01T02:00:00+00:00', '--job-id', '796', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_docker_operator.py', '--cfg-path', '/tmp/tmp6xga2t6k']
[2024-06-02T12:19:15.209+0000] {standard_task_runner.py:91} INFO - Job 796: Subtask check_status
[2024-06-02T12:19:15.553+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_docker_operator.check_status scheduled__2024-06-01T02:00:00+00:00 [running]> on host 9c47fcd741af
[2024-06-02T12:19:15.705+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_with_docker_operator' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-01T02:00:00+00:00'
[2024-06-02T12:19:15.706+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T12:19:15.729+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T12:19:15.731+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_docker_operator.py", line 24, in check_send_status
    raise ValueError(f"Check send status failed: {result}")
ValueError: Check send status failed: {'status': 'failed'}
[2024-06-02T12:19:15.751+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_with_docker_operator, task_id=check_status, run_id=scheduled__2024-06-01T02:00:00+00:00, execution_date=20240601T020000, start_date=20240602T121915, end_date=20240602T121915
[2024-06-02T12:19:15.798+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 796 for task check_status (Check send status failed: {'status': 'failed'}; 2935)
[2024-06-02T12:19:15.824+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-02T12:19:15.987+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T12:19:16.003+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
